notifications:
  email: false
git:
  quiet: true
  depth: false
language: java
jdk: openjdk8
node_js: lts/*
python: 3.7
os: linux
services: docker
addons:
  apt:
    update: true
    packages:
      - python3-setuptools
      - python3-pip
      - sudo
      - lsof
      - curl
install: true
before_install:
  - |
    if [ ! -f ${HOME}/.local/daggerok/bash-functions/master/main.bash ] ; then
      mkdir -p ${HOME}/.local/daggerok/bash-functions/master ;
      curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash > ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
    fi
    source ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
  - stop_any 80 5432 8080 8081 8082 8083 8084 8085 8086 8087 8088
  #
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user --upgrade pip
  - pip install --user --upgrade docker-compose httpie
jobs:
  include:
    - stage: test
      jdk: openjdk8
      name: fabric8-native
      script:
        - ./mvnw package -Pnative -Dquarkus.profile=docker -Dquarkus.native.container-build=true
        - ./mvnw -Pfabric8-native docker:build docker:start
        - http :8080
        - http :8080/api/hello
        - http -a user:user   :8080/api/hello/me
        - http -a max:max     :8080/api/hello/max
        - http -a admin:admin :8080/api/hello/admin
        - http -a admin:admin :8080/api/hello/me    || echo oops admin
        - http -a admin:admin :8080/api/hello/max   || echo oops max
        - ./mvnw -Pfabric8-native docker:stop docker:remove
    - stage: test
      jdk: openjdk8
      name: fabric8-jvm
      script:
        - ./mvnw -Pfabric8-jvm clean compile quarkus:build docker:build docker:start
        - http :8080
        - http :8080/api/hello
        - http -a user:user   :8080/api/hello/me
        - http -a max:max     :8080/api/hello/max
        - http -a admin:admin :8080/api/hello/admin
        - http -a admin:admin :8080/api/hello/me    || echo oops admin
        - http -a admin:admin :8080/api/hello/max   || echo oops max
        - ./mvnw -Pfabric8-jvm docker:stop docker:remove
    - stage: test
      jdk: openjdk8
      name: fabric8-pg-app
      script:
        - ./mvnw
        - ./mvnw -Pfabric8-pg-app docker:build docker:start
        - http :8080
        - http :8080/api/hello
        - http -a user:user   :8080/api/hello/me
        - http -a max:max     :8080/api/hello/max
        - http -a admin:admin :8080/api/hello/admin
        - http -a admin:admin :8080/api/hello/me    || echo oops admin
        - http -a admin:admin :8080/api/hello/max   || echo oops max
        - ./mvnw -Pfabric8-pg-app docker:stop docker:remove
    - stage: test
      jdk: openjdk8
      name: fabric8-pg + java -jar
      script:
        - ./mvnw -Pfabric8-pg docker:build docker:start
        - ./mvnw clean compile quarkus:build
        - java -jar target/*-runner.jar &
        - wait_for 8080
        - http :8080
        - http :8080/api/hello
        - http -a user:user   :8080/api/hello/me
        - http -a max:max     :8080/api/hello/max
        - http -a admin:admin :8080/api/hello/admin
        - http -a admin:admin :8080/api/hello/me    || echo oops admin
        - http -a admin:admin :8080/api/hello/max   || echo oops max
        - ./mvnw -Pfabric8-pg docker:stop docker:remove
        - stop_any 80 8080
    - stage: test
      jdk: openjdk8
      name: fabric8-pg + docker
      script:
        - ./mvnw -Pfabric8-pg docker:build docker:start
        - ./mvnw compile quarkus:build
        - docker build -f src/main/docker/Dockerfile.jvm -t quarkus/quarkus-jvm .
        - docker run -i --rm -p 8080:8080 -e POSTGRES_HOST=postgres --network quarkus-elytron-security-jdbc-postgresql-example --name app quarkus/quarkus-jvm &
        - wait_healthy_docker_containers 2
        - http :8080
        - http :8080/api/hello
        - http -a user:user   :8080/api/hello/me
        - http -a max:max     :8080/api/hello/max
        - http -a admin:admin :8080/api/hello/admin
        - http -a admin:admin :8080/api/hello/me    || echo oops admin
        - http -a admin:admin :8080/api/hello/max   || echo oops max
        - docker rm -f -v app
        - ./mvnw -Pfabric8-pg docker:stop docker:remove
    - stage: test
      jdk: openjdk8
      name: fabric8-pg + native in docker
      script:
        - ./mvnw -Pfabric8-pg docker:build docker:start
        - ./mvnw package -Pnative -Dquarkus.profile=docker -Dquarkus.native.container-build=true
        - docker build -f src/main/docker/Dockerfile.native -t quarkus/quarkus-native-app .
        - docker run -i --rm -p 8080:8080 --name app --network quarkus-elytron-security-jdbc-postgresql-example quarkus/quarkus-native-app &
        - wait_healthy_docker_containers 2
        - http :8080
        - http :8080/api/hello
        - http -a user:user   :8080/api/hello/me
        - http -a max:max     :8080/api/hello/max
        - http -a admin:admin :8080/api/hello/admin
        - http -a admin:admin :8080/api/hello/me    || echo oops admin
        - http -a admin:admin :8080/api/hello/max   || echo oops max
        - docker rm -f -v app
        - ./mvnw -Pfabric8-pg docker:stop docker:remove
    - stage: test
      jdk: openjdk11
      name: versions display-property-updates
      script: ./mvnw versions:display-property-updates
cache:
  npm: true
  pip: true
  packages: true
  directories:
    - ~/.m2
    - ~/.docker
    - ~/.local/daggerok
